### ISSUE TITLE
Deye microinverter has solved this problem!

### ISSUE THREAD

**Issue by Gladwyn2023** [s10l/deye-logger-at-cmd#2]
The software of Deye microinverter built-in Wi-Fi module had been updated, the default password of microinverter's own access point can be changed after updating.
The updated web server page as below.

![Change the password of Wi-Fi logger](https://user-images.githubusercontent.com/121864202/210474096-2f298538-b7b2-4c0f-9742-79f559e4de9a.jpg)

**Comment by s10l** [comment]
Thank you for the information, I have requested an update for my device. I will report as soon as this is done.

**Comment by astromeier** [comment]
Hi S10l, how can a request for update be done?
is an update possible if not registered in the Solarman-Cloud, but a connection with one of the 
adresses access1.solarmanpv.com or access2.solarmanpv.com established?

**Comment by s10l** [comment]
Installed firmware 1.53 and I can confirm that I was able to switch from AP+STA to AP/STA mode.

**Comment by s10l** [comment]
> Hi S10l, how can a request for update be done?
> is an update possible if not registered in the Solarman-Cloud, but a connection with one of the
> adresses access1.solarmanpv.com or access2.solarmanpv.com established?

If registered, you can send an email to service@deye.com.cn with the s/n of your logger and friendly request to schedule an update.

Its also possible to update the firmware by your own, but you need the firmware file. I will not post the url where you can downloaded the firmware.
