### ISSUE TITLE
Documented command line option `-xmbw` not available in current release

### ISSUE THREAD

**Issue by jewesta** [s10l/deye-logger-at-cmd#4]
Hi!

I just tried to write a register using the **Linux** version of main. It looks like the command -xmbw is not supported. Unfortunately I do not have access to a Win-x64 machine.

The command line I tried:

```sh
./main -t x.x.x.x:48899 -xmbw 00280001020078
```

The output I got:

```
flag provided but not defined: -xmbw
Usage of ./main:
  -t string
    	The IP and port of the loggers assistant endpoint [10.10.100.254:48899]
  -xat string
    	Send AT command instead of credentials
  -xc string
    	WiFi configuration code [WIFIKIT-214028-READ or HF-A11ASSISTHREAD] (default "WIFIKIT-214028-READ")
  -xmb string
    	Send Modbus read register instead of credentials [00120001] -> Read register 0x0012, length = 1
  -xs string
    	Local source address
  -xv
    	Outputs all communication with the logger
```

Thanks a lot in advance!

- Jens

**Comment by belzig** [comment]
You have to compile it on your own.

have a look at:
https://www.photovoltaikforum.com/thread/179529-daten-von-deye-sun-mikrowechselrichtern-abfangen/?postID=3006831#post3006831

**Comment by belzig** [comment]
Or try this one if you have a raspberry pi
[main4raspi.2rename.txt](https://github.com/s10l/deye-logger-at-cmd/files/11445771/main4raspi.2rename.txt)

**Comment by jewesta** [comment]
Thanks @belzig I wasn't aware this repo is no longer maintained. The documentation seems to be ahead of the (currently only available) release then.

I built the app on my mac. For anyone who is interested:
[main.macos.zip](https://github.com/s10l/deye-logger-at-cmd/files/11469172/main.macos.zip)

Should a new release be planned in the future feel free to contact me. I would gladly supply a mac binary.

**Comment by jewesta** [comment]
I changed the subject of this issue in light of the new information.

**Comment by denimjeans** [comment]
really sorry, off topic, do you have a link to the different modbus registers?

**Comment by belzig** [comment]
https://raw.githubusercontent.com/schwatter/solarman_mqtt/main/Deye_SUN600G3-230-EU_Register.xlsx

https://www.photovoltaikforum.com/core/attachment/337635-deye-600w-at-kommandos-befehle-returncodes-xlsx/

**Comment by denimjeans** [comment]
thank you very much, exactly what I was looking for. Modbus query is only possible via AT commands or is there any further way directly to communicate via modbus tcp protocol?

**Comment by belzig** [comment]
I recommend this thread 
https://www.photovoltaikforum.com/thread/179529-daten-von-deye-sun-mikrowechselrichtern-abfangen/?postID=3145640#post3145640

It`s very long and in German

**Comment by s10l** [comment]
Hey,

writing data could be potentially dangerous, as the program does not check any data, nor is it known how and whether the commands on the inverter are checked at all.

If you still want to write data, you must compile it yourself.
