### ISSUE TITLE
not usable on m1 macs?

### ISSUE THREAD

**Issue by vordenken** [s10l/deye-logger-at-cmd#5]
I wanted to use this on my MacBook with M1 chip and it doesn't work.
Using macOS it prints the following:
<img width="312" alt="Bildschirmfoto 2023-10-27 um 16 37 43" src="https://github.com/s10l/deye-logger-at-cmd/assets/62395860/0b6ab550-7097-4cf0-8afd-1113639f67fc">

Using a fedora vm it prints the following:
<img width="688" alt="Bildschirmfoto 2023-10-27 um 16 36 17" src="https://github.com/s10l/deye-logger-at-cmd/assets/62395860/a4dcb5e8-794a-470b-b03e-8c8a573cc76a">

**Comment by s10l** [comment]
Hey,

there are only prebuild binaries for Windows x64 and Linux x64.
You have to compile it yourself.
